### ISSUE TITLE
Request for cover when new file is fetched from radarr/sonarr + Periodic run

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#37]
Hi.
I still need to figure out how to use the radarr connector functionality to 'trigger' poster creation for that one new file/folder.

Your script does allow for one file/folder to be passed. What I'm still unclear is how can I request this from your docker from within a radarr docker. Once solved, will let you know.
I searched the web and found others have this solution, which could work great for your app as wel;.
https://hub.docker.com/r/linuxserver/radarr
Under docker_mods it lists: https://github.com/linuxserver/docker-mods/tree/radarr-striptracks
This is added to the main radarr container when installed. The script is fully accessible by Radarr (so can download a folder when available) and this can be run in parallel with the period 'refresh'; just need to use the same /config folder so the database is shared. Would something like this work? I tried simply by adding your docker to the environmental parameters of radar:
DOCKER_MODS Ilarramendi/better-covers:latest; but that doesn't seem to install. Bit stuck.. Maybe the docker-better-script should have the same linux-server 'foundation' to nicely integrate?

Clearly the other fail/safe routine, would be to periodicly run your docker; eg. every 12 hours or so. Any thought on how you think this can be achieved? (understanding you didn't like the method the amtd was using)

And before this will be used widely, I think best to think of ways to 'minimize' requests to the rating/info sites; if folks have 1000's of movies and this runs every 12 hours or so, the sites might start to block things.

**Comment by ilarramendi** [comment]
Hello! There shouldnt be a problem with the requests, since it only makes requests to scrappers/apis if metadata for media is missing of `metadataDate - today > metadataUpdateInterval`, the same for mediainfo.
About the docker cointainers, that could be a good idea and ill probably implement it for the people that dont use a media agent, but i think would be more usefull to have a standalone docker container that periodicaly checks the emby/jf/plex api for new media to generate covers and update library, Also that wouldnt mess with any container and allows to still run vanilla versions of them.
What do you think about that?

**Comment by michpas** [comment]
Hi.
On 1. metadataDate - today > metadataUpdateInterval.
How does this work? Is metadataUpdateinterval set by an environmental variable?
I guess it's a static value; not sure if this meets the best user case as:
for new releases, it's key to relative frequently (daily) update the rating; but for older movies the ratings hardly change, so a update of monthly or quaterly is maybe needed. With large libraries (1000+ movies) this can be tricky if it's a static number of days. Either the frequency is too low for new covers or too high for existing.
Maybe a way to do this is to have a count value: 'refresh_after_x_days', which increments with every time a refresh is run.
Eg.  MetadataDate+refresh_after_x_days < today run the refresh routine and increase the refresh_after_x-days by the square root of the refresh_after_x_days value itself. With refresh_after_x_days starting at value 1 on first initial run.

This would give.
1-Sep-2021: No poster: Create initial + SetRefresh_after_x_days to 1
2-Sep-2021: MetadataData (1-Sep-2021) +1 day <= 2-Sep 2021; yes.  Create new poster and 
    SetRefresh_after_x_days = SetRefresh_after_x_days + SquareRoot of SetRefresh_after_x_days. e.g. SetRefresh_after_x_days= 1+1=2

3-Sep-2021: MetadataData (2-Sep-2021) +2 days <= 3-Sep 2021; no; No run

4-Sep-2021: MetadataData (2-Sep-2021) +2 days <= 4-Sep 2021; yes; create new poster and
    SetRefresh_after_x_days = SetRefresh_after_x_days + SquareRoot of SetRefresh_after_x_days. e.g. SetRefresh_after_x_days= 2+1.4 =3.4

5-Sep-2021: MetadataData (4-Sep-2021) +3.4 days <= 5-Sep 2021; no, no run
6-Sep-2021: MetadataData (4-Sep-2021) +3.4 days <= 6-Sep 2021; no, no run
7-Sep-2021: MetadataData (4-Sep-2021) +3.4 days <= 7-Sep 2021; yes; create new poster and
    SetRefresh_after_x_days = SetRefresh_after_x_days + SquareRoot of SetRefresh_after_x_days. e.g. SetRefresh_after_x_days= 3.4 3.4+1.8 =5.2

8-Sep-2021: MetadataData (7-Sep-2021) +5.2 days <= 8-Sep 2021; no run
9-Sep-2021: MetadataData (7-Sep-2021) +5.2 days <= 9-Sep 2021; no run
10-Sep-2021: MetadataData (7-Sep-2021) +5.2 days <= 10-Sep 2021; no run
11-Sep-2021: MetadataData (7-Sep-2021) +5.2 days <= 11-Sep 2021; no run
12-Sep-2021: MetadataData (7-Sep-2021) +5.2 days <= 12-Sep 2021; yes, create new poster.

This mechanism would slightly reduce the requery/fecthing of the poster over time. In the beginning quite often, later on, much less.  If is reduced too quickly, you can also half the square_root value.


Hope this is not too cnnfusing.

On 2.

Yes, fully agree, A standalone cdocker that runs periodcicly is def a good offer; however this does mean that for new titles added , the new cover is only generated on the cycle *and not imemediately.  Which  wouyld be nicerr.

y

**Comment by michpas** [comment]
Yeah. You are right. It should indeed be based on the date of media. Older files (even fetched recently) should also be updated infrequently.
I guess static is also not the answer; How would you suggest to make this dynamic so that:

1) Older movies released  have a very low frequency 
2) Newer movies get a higher refresh rate, but with a lower frequency?

Maybe the algoritme is the logic of the above, but with the initial  ''Refresh_after_x_days'' set to a value (for example number of months between movie date and date of initial creation) and afterthat the refresh after x days to be increased by the square root of the value itself. This would tick al boxed.

Eg. older movies would by default start with a high value; newer movies start with a lower count (eg. refresh more often); but on every refresh, the next one will be longer.

**Comment by ilarramendi** [comment]
I was thinking something smimilar like what you said, like: roundUp(sqrt(daysSinceRelease))
This would generate:
| Day | Next Update |
| -----| -------------- |
| 0     | 1 day             |
| 0     | 1 day             |
| 0                             | 1 day             |
| 0                             | 1 day             |
| 0                             | 1 day             |

| 1                            | True       | 
| 1                            | True       | 
| 1                            | True       | 
| 1                            | True       | 
| 1                            | True       |

**Comment by ilarramendi** [comment]
I was thinking something smimilar like what you said, like: roundUp(sqrt(daysSinceRelease))
This would generate:
| Day since rl | Next Update |
| ------------ | -------------- |
| 0                 | 1 day             |
| 1                 | 1 day             |
| 2                 | 2 days            |
| 2                 | 2 days            |
| 2                 | 2 days            |
| 1                 | 1 day             |
| 1                 | 1 day             |

| 0                             | 1 day             |
| 0                             | 1 day             |
| 0                             | 1 day             |

| 1                            | True       | 
| 1                            | True       | 
| 1                            | True       | 
| 1                            | True       | 
| 1                            | True       |

**Comment by ilarramendi** [comment]
I was thinking something smimilar like what you said, like: `int(sqrt(daysSinceRelease * 4 + 1))`
This would update on days:
| Day since rl | Next Update |
| ------------ | -------------- |
| 0                 | 1 day             |
| 1                 | 2 day             |
| 3                 | 3 days            |
| 6                 | 5 days            |
| 11               | 6 days            |
| 17               | 8 days            |
| 25               | 10 days          |
| 35               | 11 days          |
| 46               | 13 days          |
| 59               | 15 days          |
| 74               | 17 days          |
| 91               | 19 days          |
| 120             | 21 days          |
| 141             | 23 days          |
| 164             | 25 days          |
| 189             | 27 days          |
| 216             | 29 days          |
| 245             | 31 days          |
| 276             | 33 days          |
| 309             | 35 days          |
| 344             | 37 days          |

Up to a maximum of 60 days for movies of aprox 3 year maby?
IMO values should only deppend from the date, not the previous value.

**Comment by michpas** [comment]
Nice. Great idea.
Good thing about this approach is that also the load (of queries)'is spread. 
I would fine-tune the max. as that would generate otherwise a peak (some people might have huge libraries of old stuff). Eg all older movies are refreshed at the same. Better would be to randomize these, by for example adding rand(30) days

**Comment by ilarramendi** [comment]
Done on v0.9, didnt set a time limit to update, maby ill set it to a realy large value in the future, that way its only a problem for a small number of movies once in a while.
