### ISSUE TITLE
start on radarr fetched movie

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#38]
Hi. Wanted to let you know I also figured out how to easily start your container.

Used portainer
and and script in Radarr (on video import) that runs a bash script that communicates to the portainer api to start your docker.

Works great !

**Comment by ilarramendi** [comment]
Relay nice solution, that would allow to have the default version of radarr/sonarr running!
Also i just released v0.9 with a lot of new features, you can read the update log [here](https://github.com/ilarramendi/Cover-Ratings/pull/35). And its recommended to read the README (still a wip) since a lot changed on the config file since last version.
PD: Things like this can be talked on the discussions tab, no need to open a new PR.
