### ISSUE TITLE
Poster Language

### ISSUE THREAD

**Issue by memnos** [ilarramendi/Cover-Ratings#46]
Hello,
i've just seen your script.
I gave a look on all settings, but i didn't find if there is the possibility to select the language of the downloaded poster or it is just possible to download English one?

**Comment by ilarramendi** [comment]
Hello! 
Its been a while but im having free time again so i started working in this project again!
You can change the prefered image language inside config.json with the option: `preferedImageLanguage`
PD: Project was moved to: https://github.com/ilarramendi/BetterCovers
PD2: Docker version works but is 50% slower idk why, i recommend if you want to try the new version run the python script instead of using the container.
Have a great day!
