### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by samcro1967** [ilarramendi/Cover-Ratings#48]
Thank you for this.  Working very well, but I have some questions...

1. It looks like the script continuously runs in the docker container.  Is there a way to have it run every 5 or 10 mins.  That way it is not continuously running waiting for the API limit to expire and sending more requests to the APIs or does it no longer send once the limit is reached and waits for a period of time before sending more requests?
2. Looks like all of the ones it generated are good with the exception of one movie, Arthur 2011.  It is just a blank black poster.  Not sure how to deal with one movie when it finds an incorrect match.
3. Not having any luck setting the timezone for the container so the date and time is correct in the logs.  I mounted /etc/timezone:/etc/timezone:ro in the container and the timezone file in the container is correct, but the date and time in the logs is not.

**Comment by ilarramendi** [comment]
Hello!
1) The docker container runs only once for all media that you pass to the container and its removed, but the container is a bit buggy i think because i changed the base image, i would recommend to run the python script instead of the container ATM.
2) Some times a black image is generated if you are using a lot of workers, thats because there isnt enought time to download the image from TMDB, try using a lower amount in `-w` or generate the image for that specific movie again using the parameter `-o`
3) This is the first docker image i created so im not sure how to fix this, i tried mounting `/etc/timezone` and setting an enviromental variable using `tzdata` but it didnt work, ill take a look at this a bit more in depth later!
